In [ ]:
import pandas as pd
import random
from datetime import datetime, timedelta

# Define constants
start_date = datetime(2022, 9, 1, 7, 0)
end_date = datetime(2023, 8, 31, 22, 0)
business_types = ["Supermarket", "Convenience Store", "Drugstore", "Discount Store", "Home Center"]
payment_methods = ["Cash", "Credit", "Debit"]
genders = ["Male", "Female", "Other"]
age_categories = ["Children", "Youth", "Middle-aged", "Elderly"]
product_names = [f"Product_{i}" for i in range(1, 1001)]

# Initialize data list
data = []

# Helper function to categorize age
def categorize_age(age):
    if age <= 20:
        return "Children"
    elif age <= 40:
        return "Youth"
    elif age <= 60:
        return "Middle-aged"
    else:
        return "Elderly"

# Helper function to generate random datetime within business hours
def random_business_hour_time():
    return start_date + timedelta(minutes=random.randint(0, 15*60))

# Initialize variables
transaction_id = 1
user_id = 1
receipt_id = 1
jan_code = 1

# Generate data
while start_date <= end_date:
    user_age = random.randint(1, 80)
    user_age_category = categorize_age(user_age)
    user_gender = random.choice(genders)
    business_type = random.choice(business_types)
    purchase_time = random_business_hour_time()
    product = random.choice(product_names)
    unit_price = round(random.uniform(1, 100), 2)
    quantity = random.randint(1, 3)
    subtotal = unit_price * quantity
    payment_method = random.choice(payment_methods)

    data.append([transaction_id
                 , receipt_id
                 , user_id
                 , purchase_time
                 , purchase_time.strftime("%A")
                 , business_type
                 , user_gender
                 , user_age_category
                 , product
                 , unit_price
                 , quantity
                 , subtotal
                 , payment_method
                 , jan_code]
                )

    transaction_id += 1
    receipt_id += 1
    jan_code += 1

    # Generate a new transaction for a new user
    if random.random() < 0.2:
        user_id += 1
        transaction_id = 1

    start_date += timedelta(minutes=random.randint(10, 120))

# Create a DataFrame
df = pd.DataFrame(data, columns=["Transaction ID", "Receipt ID", "User ID", "Date/Time", "Day of the Week", "Business Type", "Gender", "Age", "Product Name", "Unit Price", "Quantity Purchased", "Subtotal", "Payment Method", "Jan Code"])

# Save data to a .csv file
df.to_csv("sales_data.csv", index=False)

In [ ]:
print(df)

      Transaction ID  Receipt ID  User ID           Date/Time Day of the Week  \
0                  1           1        1 2022-09-01 18:28:00        Thursday
1                  2           2        1 2022-09-01 22:47:00        Thursday
2                  1           3        2 2022-09-01 14:56:00        Thursday
3                  2           4        2 2022-09-01 22:29:00        Thursday
4                  1           5        3 2022-09-01 18:05:00        Thursday
...              ...         ...      ...                 ...             ...
8127               5        8128     1682 2023-08-31 18:15:00        Thursday
8128               1        8129     1683 2023-09-01 07:25:00          Friday
8129               2        8130     1683 2023-08-31 23:40:00        Thursday
8130               1        8131     1684 2023-08-31 21:18:00        Thursday
8131               2        8132     1684 2023-09-01 07:06:00          Friday

          Business Type  Gender          Age Product Name  Unit Price  \
0        Discount Store    Male      Elderly  Product_500       42.96
1             Drugstore   Other      Elderly  Product_177       90.30
2     Convenience Store   Other      Elderly  Product_192       14.57
3        Discount Store  Female  Middle-aged  Product_673       66.96
4        Discount Store    Male  Middle-aged  Product_929       59.88
...                 ...     ...          ...          ...         ...
8127     Discount Store  Female      Elderly  Product_124       43.31
8128        Supermarket   Other  Middle-aged  Product_288       60.42
8129     Discount Store    Male        Youth  Product_837       30.62
8130        Home Center    Male     Children  Product_772       68.03
8131        Home Center   Other  Middle-aged  Product_154       81.82

      Quantity Purchased  Subtotal Payment Method  Jan Code
0                      2     85.92          Debit         1
1                      1     90.30         Credit         2
2                      1     14.57         Credit         3
3                      1     66.96           Cash         4
4                      1     59.88          Debit         5
...                  ...       ...            ...       ...
8127                   2     86.62           Cash      8128
8128                   3    181.26           Cash      8129
8129                   3     91.86          Debit      8130
8130                   3    204.09         Credit      8131
8131                   2    163.64           Cash      8132

[8132 rows x 14 columns]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

df.to_csv('/content/drive/My Drive/output.csv', index=False)

Mounted at /content/drive